export function buildStyles(p) {
  return {
    body: {
      minHeight: "100vh",
      background: `${p.bgGradient}, ${p.bg}`,
      fontFamily: "-apple-system, BlinkMacSystemFont, Inter, 'Helvetica Neue', sans-serif",
      color: p.ink,
      padding: "16px",
      position: "relative",
      fontSize: 15,
    },
    // maxWidth kaldırıldı — sidebar tam sola yaslı, ana içerik ekranın tamamını kullanır.
    // "1fr" tek başına minmax(auto,1fr) demektir — geniş bir tablo geldiğinde sütun küçülmeyip
    // sayfayı ekran dışına taşırır, o yüzden minmax(0,1fr) kullanıyoruz (bkz. konuşma)
    shell: { width: "100%", display: "grid", gridTemplateColumns: "244px minmax(0, 1fr)", gap: 16 },
    sidebar: { background: p.panel, backdropFilter: "blur(18px)", border: `1px solid ${p.line}`, borderRadius: 16, padding: "22px 16px", height: "fit-content", boxShadow: p.shadow },
    brand: { display: "flex", alignItems: "center", gap: 10, padding: "2px 8px 20px", justifyContent: "space-between" },
    brandLeft: { display: "flex", alignItems: "center", gap: 10 },
    brandMark: { width: 24, height: 24, borderRadius: 6, background: p.accentGrad, flexShrink: 0 },
    brandName: { fontWeight: 600, fontSize: 16, letterSpacing: "-0.01em" },
    themeToggle: { display: "flex", alignItems: "center", gap: 3, background: p.fieldBg, borderRadius: 20, padding: 3, cursor: "pointer" },
    themeToggleBtn: { width: 24, height: 24, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12 },
    themeToggleBtnActive: { background: p.panelSolid, boxShadow: p.shadow },
    navLabel: { fontSize: 11.5, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.06em", color: p.inkSoft, padding: "16px 10px 7px" },
    deptList: { display: "flex", flexDirection: "column", gap: 3 },
    deptItem: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "10px 11px", borderRadius: 8, cursor: "pointer", fontSize: 14.5, color: p.ink },
    deptItemActive: { background: p.accentSoft, color: p.accent, fontWeight: 600 },
    deptLeft: { display: "flex", alignItems: "center", gap: 10 },
    deptDot: { width: 6, height: 6, borderRadius: "50%", background: p.neutralDot, display: "inline-block" },
    deptDotActive: { background: p.accent },
    deptCount: { fontSize: 12.5, color: p.inkSoft, fontFamily: "monospace" },
    deptCountActive: { color: p.accent },
    main: { display: "flex", flexDirection: "column", gap: 16 },
    // Global footer (madde 1) — shell grid'inin her iki sütununu kapsar, altta durur.
    appFooter: {
      gridColumn: "1 / -1", marginTop: 6, padding: "14px 20px",
      background: p.panel, border: `1px solid ${p.line}`, borderRadius: 14, boxShadow: p.shadow,
      display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 8,
      fontSize: 12.5,
    },
    panel: { background: p.panel, backdropFilter: "blur(18px)", border: `1px solid ${p.line}`, borderRadius: 16, boxShadow: p.shadow, overflowX: "auto", minWidth: 0 },
    pageTitle: { fontSize: 26, fontWeight: 800, margin: "0 0 5px", letterSpacing: "-0.015em" },
    pageSub: { fontSize: 14, color: p.inkSoft, margin: 0 },
    statStrip: { display: "flex", gap: 26, marginTop: 18, paddingTop: 18, borderTop: `1px solid ${p.line}` },
    stat: { display: "flex", flexDirection: "column", gap: 3 },
    statNum: { fontSize: 22, fontWeight: 600, fontFamily: "monospace", letterSpacing: "-0.02em" },
    statLabel: { fontSize: 12.5, color: p.inkSoft },
    toolbar: { display: "flex", flexDirection: "column", gap: 11, padding: "16px 24px" },
    toolbarFiltersRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
    toolbarActionsRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", justifyContent: "flex-end" },
    searchWrap: { display: "flex", alignItems: "center", gap: 8, background: p.fieldBg, borderRadius: 8, padding: "9px 13px", flex: "1 1 150px", minWidth: 160, maxWidth: 250 },
    searchInput: { border: "none", background: "transparent", fontSize: 14.5, width: "100%", fontFamily: "inherit", color: p.ink },
    searchClear: { cursor: "pointer", color: p.inkSoft, fontSize: 12, flexShrink: 0, padding: "2px 3px" },
    // Metin ("Zimmet Doğru", "Monitör Uyuşmazlığı" gibi) dar bir satırda kalınca sarmalanıp
    // segment butonlarını çirkin iki satırlı kutucuklara çeviriyordu — bkz. konuşma ("bu kısım
    // bence güzel durmuyor"). whiteSpace:nowrap + overflowX:auto ile taşarsa yatay kaydırılır,
    // asla satır kırmaz.
    segmented: { display: "flex", background: p.fieldBg, borderRadius: 8, padding: 2, overflowX: "auto", maxWidth: "100%" },
    seg: { padding: "7px 15px", fontSize: 13.5, borderRadius: 6, color: p.inkSoft, cursor: "pointer", whiteSpace: "nowrap", flexShrink: 0 },
    segActive: { background: p.panelSolid, boxShadow: p.shadow, fontWeight: 600, color: p.ink },
    chipToggle: { fontSize: 13, color: p.inkSoft, background: p.fieldBg, padding: "8px 13px", borderRadius: 8, cursor: "pointer" },
    // display: "inline-flex" (flex DEĞİL) — "flex" blok seviyeli kutu ürettiği için birden fazla
    // buton yan yana (ör. bir tablo satırının Aksiyon hücresinde) konduğunda her biri kendi
    // satırına düşüp dikey istifleniyordu; bu da satır yüksekliğini anormal şişiriyordu (bkz.
    // konuşma — "Kayıtlar kısmında çok fazla boşluk var"). inline-flex, buton içindeki ikon+metin
    // hizalamasını korurken butonun kendisini satır içi (yan yana dizilebilir) yapıyor.
    btnGhost: { border: "none", borderRadius: 8, padding: "9px 16px", fontSize: 13.5, fontWeight: 600, cursor: "pointer", display: "inline-flex", alignItems: "center", gap: 6, fontFamily: "inherit", background: p.fieldBg, color: p.ink },
    btnPrimary: { border: "none", borderRadius: 8, padding: "9px 16px", fontSize: 13.5, fontWeight: 600, cursor: "pointer", display: "inline-flex", alignItems: "center", gap: 6, fontFamily: "inherit", background: p.accent, color: "#fff" },
    table: { width: "100%", borderCollapse: "collapse" },
    th: { textAlign: "left", fontSize: 14.5, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.03em", color: p.ink, padding: "13px 24px", borderBottom: `2px solid ${p.line}`, whiteSpace: "nowrap" },
    td: { padding: "14px 24px", borderBottom: `1px solid ${p.line}`, fontSize: 14.5 },
    cellName: { fontWeight: 600, display: "flex", alignItems: "center", gap: 6 },
    clickableName: { cursor: "pointer", textDecoration: "underline", textDecorationColor: p.accentSoft, textUnderlineOffset: 2 },
    cellSub: { color: p.inkSoft, fontSize: 12.5, marginTop: 2 },
    // Seri no birincil/tanımlayıcı bilgi olduğu için tam kontrastlı (p.ink) — önceden inkSoft
    // (soluk gri) kullanıyordu, okunurluğu düşüyordu (bkz. konuşma)
    serial: { fontFamily: "monospace", fontSize: 13.5, fontWeight: 600, color: p.ink },
    badge: { display: "inline-flex", alignItems: "center", gap: 5, padding: "5px 11px", borderRadius: 20, fontSize: 12, fontWeight: 600 },
    badgeDot: { width: 6, height: 6, borderRadius: "50%", display: "inline-block" },
    badgeOk: { background: p.okBg, color: p.ok },
    badgeBad: { background: p.badBg, color: p.bad },
    badgeNeutral: { background: p.neutralBg, color: p.inkSoft },
    dupTag: { fontSize: 11, fontWeight: 600, color: p.warnFg, background: p.warnBg, padding: "2px 8px", borderRadius: 10 },
    opsCell: { display: "flex", alignItems: "center", gap: 6 },
    statusPill: { fontSize: 12, fontWeight: 600, padding: "5px 10px", borderRadius: 20, cursor: "pointer", whiteSpace: "nowrap" },
    noteInput: { fontSize: 13, border: p.fieldBorder, borderRadius: 6, padding: "6px 9px", width: 120, fontFamily: "inherit", background: p.white, color: p.ink },
    iconBtnSmall: { width: 28, height: 28, borderRadius: 6, border: p.fieldBorder, background: p.white, color: p.ink, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", fontSize: 13, flexShrink: 0 },
    iconBtnSmallActive: { background: p.accent, color: "#fff", border: `1px solid ${p.accent}` },
    tableFooter: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "13px 24px", fontSize: 12.5, color: p.inkSoft, borderTop: `1px solid ${p.line}` },
    checkbox: { width: 16, height: 16, cursor: "pointer", accentColor: p.accent },
    rowSelected: { background: p.accentSoftStrong },
    toast: { position: "fixed", bottom: 24, left: "50%", transform: "translateX(-50%)", background: p.toastBg, color: p.toastFg, padding: "11px 20px", borderRadius: 10, fontSize: 14, boxShadow: "0 8px 24px rgba(0,0,0,0.25)", maxWidth: 440, textAlign: "center" },
    modalOverlay: { position: "fixed", inset: 0, background: p.overlay, display: "flex", alignItems: "center", justifyContent: "center", zIndex: 50, padding: 24 },
    modalCard: { background: p.panelSolid, color: p.ink, borderRadius: 16, padding: "26px 28px", width: "min(680px, 100%)", maxHeight: "80vh", overflowY: "auto", boxShadow: p.modalShadow },
    modalHeader: { display: "flex", alignItems: "center", justifyContent: "space-between" },
    modalTitle: { fontSize: 19, fontWeight: 650, margin: 0, letterSpacing: "-0.01em" },
    modalClose: { cursor: "pointer", fontSize: 17, color: p.inkSoft, padding: 4 },
    modalSub: { fontSize: 13.5, color: p.inkSoft, margin: "4px 0 18px" },
    dashRowHead: { display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 7 },
    dashDeptName: { fontSize: 15.5, fontWeight: 600 },
    dashDeptTotal: { fontSize: 12.5, color: p.inkSoft, fontFamily: "monospace" },
    dashBar: { display: "flex", height: 15, borderRadius: 7, overflow: "hidden", background: p.fieldBg },
    dashBarSeg: { height: "100%" },
    dashLegendRow: { display: "flex", gap: 18, marginTop: 7 },
    dashLegendItem: { fontSize: 12.5, color: p.inkSoft, display: "flex", alignItems: "center", gap: 5 },
    dashDot: { width: 7, height: 7, borderRadius: "50%", display: "inline-block" },
    kpiGrid: { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 16 },
    kpiCard: { background: p.fieldBg, borderRadius: 12, padding: "16px 18px", display: "flex", flexDirection: "column", gap: 6 },
    kpiValue: { fontSize: 26, fontWeight: 700, fontFamily: "monospace", letterSpacing: "-0.02em", lineHeight: 1 },
    kpiLabel: { fontSize: 12.5, color: p.inkSoft },
    kpiSub: { fontSize: 11.5, fontWeight: 600 },
    dashboardTwoCol: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 30 },
    dashboardCol: { display: "flex", flexDirection: "column", gap: 15 },
    donutRow: { display: "flex", alignItems: "center", gap: 24 },
    legendCol: { display: "flex", flexDirection: "column", gap: 10, flex: 1 },
    legendItemRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, fontSize: 13.5 },
    legendItemLeft: { display: "flex", alignItems: "center", gap: 8 },
    legendDot: { width: 8, height: 8, borderRadius: "50%", display: "inline-block", flexShrink: 0 },
    legendCount: { fontFamily: "monospace", fontWeight: 600, fontSize: 13.5 },
    groupedBarBlock: { display: "flex", flexDirection: "column", gap: 8 },
    groupedBarHead: { display: "flex", justifyContent: "space-between", fontSize: 13.5 },
    groupedBarDeptName: { fontWeight: 600 },
    groupedBarTrack: { display: "flex", height: 12, borderRadius: 6, overflow: "hidden", background: p.fieldBg },
    reportTypeGroup: { display: "flex", flexDirection: "column", gap: 13 },
    reportTypeLabel: { fontSize: 12, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.05em", color: p.inkSoft, marginBottom: 5 },
    settingsSectionHead: { display: "flex", alignItems: "center", gap: 9 },
    demoTag: { fontSize: 10.5, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.04em", color: p.warnFg, background: p.warnBg, padding: "3px 9px", borderRadius: 20 },
    formGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginTop: 18 },
    formField: { display: "flex", flexDirection: "column", gap: 7 },
    formFieldWide: { display: "flex", flexDirection: "column", gap: 7, gridColumn: "1 / -1" },
    formLabel: { fontSize: 13, fontWeight: 600, color: p.ink },
    formInput: { fontSize: 14.5, border: p.fieldBorder, borderRadius: 8, padding: "10px 13px", fontFamily: "inherit", background: p.white, color: p.ink, width: "100%" },
    formTextarea: { fontSize: 13.5, border: p.fieldBorder, borderRadius: 8, padding: "10px 13px", fontFamily: "monospace", background: p.white, color: p.ink, width: "100%", minHeight: 160, resize: "vertical" },
    formCheckRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 14 },
    formHelper: { fontSize: 12.5, color: p.inkSoft, margin: "11px 0 0" },
    formActions: { display: "flex", alignItems: "center", gap: 10, marginTop: 18 },
    settingsSectionTitle: { fontSize: 23, fontWeight: 800, margin: "0 0 6px", letterSpacing: "-0.015em" },
    scheduleRow: { display: "flex", alignItems: "center", gap: 12, marginTop: 15, flexWrap: "wrap" },
    scheduleLabel: { display: "flex", alignItems: "center", gap: 7, fontSize: 14 },
    scheduleSelect: { fontSize: 14, border: p.fieldBorder, borderRadius: 8, padding: "8px 11px", fontFamily: "inherit", background: p.white, color: p.ink },
    filterSaveRow: { display: "flex", alignItems: "center", gap: 6 },
    savedFilterBar: { display: "flex", alignItems: "center", gap: 8, padding: "0 24px 15px", flexWrap: "wrap" },
    savedFilterLabel: { fontSize: 12.5, color: p.inkSoft },
    savedFilterChip: { display: "inline-flex", alignItems: "center", gap: 6, background: p.accentSoftStrong, color: p.accent, padding: "6px 11px", borderRadius: 20, fontSize: 13, cursor: "pointer" },
    savedFilterRemove: { fontSize: 11, color: p.bad, cursor: "pointer" },

    // --- Görünüm anahtarı (Klasik / Yoğun / Detay) ---
    layoutSwitch: { display: "flex", background: p.fieldBg, borderRadius: 8, padding: 2, gap: 2 },
    layoutSwitchBtn: { flex: 1, textAlign: "center", padding: "7px 4px", borderRadius: 6, fontSize: 12, fontWeight: 600, color: p.inkSoft, cursor: "pointer" },
    layoutSwitchBtnActive: { background: p.panelSolid, color: p.accent, boxShadow: p.shadow },

    // --- KPI şeridi tıklanabilirlik ---
    statClickable: { cursor: "pointer", borderRadius: 8, padding: "4px 8px", margin: "-4px -8px" },
    statActive: { background: p.accentSoft },

    // --- Yoğun ızgara (1b) ---
    denseTh: { textAlign: "left", fontSize: 13.5, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.035em", color: p.ink, padding: "11px 11px", borderBottom: `2px solid ${p.line}`, background: p.fieldBg, cursor: "default", userSelect: "none", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
    denseThSortable: { cursor: "pointer" },
    denseTd: { padding: "0 11px", fontSize: 13.5, height: 40, display: "flex", alignItems: "center" },
    denseRow: { display: "grid", alignItems: "stretch", borderBottom: `1px solid ${p.line}` },
    denseStripe: { width: 3, alignSelf: "stretch" },
    denseSerial: { fontFamily: "monospace", fontSize: 13, color: p.ink },

    // --- Kart + Detay (1c) ---
    detailLayoutRow: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) 460px", gap: 18, alignItems: "start" },
    cardList: { display: "flex", flexDirection: "column", gap: 7, padding: "14px 16px" },
    cardListHeader: { display: "grid", gridTemplateColumns: "20px 120px 2fr 1fr 120px 16px", alignItems: "center", gap: 12, padding: "0 12px 9px", fontSize: 13.5, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.035em", color: p.ink, borderBottom: `2px solid ${p.line}`, marginBottom: 4, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
    cardRow: { display: "grid", gridTemplateColumns: "20px 120px 2fr 1fr 120px 16px", alignItems: "center", gap: 12, padding: "12px 12px", borderRadius: 10, background: p.fieldBg, border: "1px solid transparent", cursor: "pointer" },
    cardRowSerial: { fontFamily: "monospace", fontSize: 14.5, fontWeight: 700, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    cardRowName: { fontSize: 14, fontWeight: 600, color: p.ink, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    cardRowLocation: { fontSize: 13.5, color: p.inkSoft, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    cardRowSelected: { border: `1px solid ${p.accent}`, background: p.accentSoftStrong },
    cardRowUnmatched: { border: `1px solid ${p.badBg}` },
    cardChevron: { textAlign: "right", color: p.inkSoft, fontSize: 16 },
    detailAside: { background: p.panel, backdropFilter: "blur(18px)", border: `1px solid ${p.line}`, borderRadius: 16, boxShadow: p.shadow, padding: 32, display: "flex", flexDirection: "column", gap: 22, position: "sticky", top: 20, fontSize: 16, minWidth: 0, maxWidth: "100%", overflowWrap: "break-word" },
    detailEmpty: { fontSize: 14.5, color: p.inkSoft, textAlign: "center", padding: "44px 12px" },
    detailAvatar: { width: 60, height: 60, borderRadius: 14, background: p.accentSoft, color: p.accent, display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 700, fontSize: 19, fontFamily: "monospace", flexShrink: 0 },
    // gap eklendi: değer kısa olduğunda (ör. "SUBE-C") space-between zaten geniş boşluk
    // bırakıyordu, ama uzun bir cümle (ör. Kullanılmayan Cihazlar'daki inaktif açıklama metni)
    // satırı doldurup "boşta kalan alanı" sıfırlayınca etiket ve değer bitişik/boşluksuz
    // görünüyordu (bkz. konuşma — ekran görüntüsüyle işaretlendi: "ModelSYNOB000000..."). gap,
    // içerik ne kadar uzun olursa olsun aralarında asgari boşluğu garanti eder.
    detailFieldRow: { display: "flex", justifyContent: "space-between", gap: 14, padding: "15px 0", borderBottom: `1px solid ${p.line}`, fontSize: 15.5 },
    detailAlert: { padding: "16px 18px", borderRadius: 10, background: p.badBg, border: `1px solid ${p.bad}33` },
    detailAlertTitle: { fontSize: 15, fontWeight: 700, color: p.bad },
    detailAlertBody: { marginTop: 5, fontSize: 14, lineHeight: 1.55, color: p.inkSoft },

    // --- Kayan toplu işlem çubuğu (detay modu) ---
    floatingBar: { position: "fixed", left: "50%", transform: "translateX(-50%)", bottom: 24, display: "flex", alignItems: "center", gap: 14, padding: "13px 20px", borderRadius: 14, background: p.toastBg, color: p.toastFg, boxShadow: "0 12px 30px rgba(0,0,0,.35)", zIndex: 40 },
    floatingBarLabel: { fontSize: 13.5, fontWeight: 600 },
  };
}
